version: '2.1'

services:
  robot-framework-target:
    tty: true
    image: rpartapsing/dsh:part1 #dockerrfpy27
    volumes:
      - ./Testcases:/robot/Testcases
      - ./requirements:/robot/requirements
      - ./Testresults:/robot/Testresults
    container_name: dockerrfpy27
    working_dir: /robot
    depends_on:
      kafka:
        condition: service_healthy
    links:
      - kafka
    entrypoint: bash -lc "source venv/bin/activate && pybot -d Testresults Testcases/"
    #entrypoint: sleep 1h

  kafka:
    image: landoop/fast-data-dev
    container_name: dkafka
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "9092:9092"
    environment:
      - ADV_HOST=kafka
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3030"]
        interval: 30s
        timeout: 10s
        retries: 5